package clyvasync.Clyvasync.exception;

import lombok.Getter;
import org.springframework.http.HttpStatus;
import org.springframework.http.HttpStatusCode;

@Getter
public enum ResultCode {
    SUCCESS(1000, HttpStatus.OK),
    FAILED(9000, HttpStatus.INTERNAL_SERVER_ERROR),

    // --- 1xxx: Authentication & Authorization ---
    UNAUTHENTICATED(1001, HttpStatus.UNAUTHORIZED),
    ACCESS_DENIED(1002, HttpStatus.FORBIDDEN),
    TOKEN_EXPIRED(1003, HttpStatus.UNAUTHORIZED),
    INVALID_TOKEN(1004, HttpStatus.UNAUTHORIZED),
    LOGIN_FAILED(1005, HttpStatus.UNAUTHORIZED),
    USER_NOT_ACTIVE(1006, HttpStatus.FORBIDDEN),
    USER_ALREADY_ACTIVE(1007, HttpStatus.BAD_REQUEST),
    LOGOUT_SUCCESS(1008, HttpStatus.OK),
    LOGOUT_FAILED(1009, HttpStatus.INTERNAL_SERVER_ERROR),
    ACCOUNT_TEMPORARILY_LOCKED(1010, HttpStatus.FORBIDDEN),
    DEVICE_NOT_FOUND(1011, HttpStatus.NOT_FOUND),

    // --- 11xx: Verification (OTP / Captcha) ---
    OTP_INVALID(1101, HttpStatus.BAD_REQUEST),
    OTP_EXPIRED(1102, HttpStatus.BAD_REQUEST),
    OTP_VALID(1103, HttpStatus.OK),
    CAPTCHA_REQUIRED(1104, HttpStatus.BAD_REQUEST),
    CAPTCHA_INVALID(1105, HttpStatus.BAD_REQUEST),
    EMAIL_IS_SPAM(1106, HttpStatus.BAD_REQUEST),
    PLEASE_WAIT_BEFORE_RESENDING(1107, HttpStatus.TOO_MANY_REQUESTS),
    OTP_REQUIRED(1108, HttpStatus.BAD_REQUEST),
    EMAIL_INVALID(1109, HttpStatus.BAD_REQUEST),

    // --- 2xxx: User & Profile Management ---
    USER_NOT_FOUND(2001, HttpStatus.NOT_FOUND),
    USER_EXISTED(2002, HttpStatus.CONFLICT),
    EMAIL_ALREADY_USED(2003, HttpStatus.CONFLICT),
    USERNAME_INVALID(2004, HttpStatus.BAD_REQUEST),
    PASSWORD_INVALID(2005, HttpStatus.BAD_REQUEST),
    PASSWORD_TOO_WEAK(2006, HttpStatus.BAD_REQUEST),
    PASSWORD_NOT_MATCH(2007, HttpStatus.BAD_REQUEST),
    CURRENT_PASSWORD_INCORRECT(2008, HttpStatus.BAD_REQUEST),
    NEW_PASSWORD_SAME_AS_OLD(2009, HttpStatus.BAD_REQUEST),
    REGISTER_SUCCESS(2010, HttpStatus.CREATED),
    ACTIVATION_SUCCESS(2011, HttpStatus.OK),
    PASSWORD_RESET_SUCCESS(2012, HttpStatus.OK),
    PASSWORD_CHANGED_SUCCESS(2013, HttpStatus.OK),
    EMAIL_VERIFICATION_SENT(2014, HttpStatus.OK),
    HOST_VERIFICATION_REQUIRED(2015, HttpStatus.FORBIDDEN), // Yêu cầu KYC chủ nhà

    // --- 3xxx: Homestay & Tour Management ---
    HOMESTAY_NOT_FOUND(3001, HttpStatus.NOT_FOUND),
    TOUR_NOT_FOUND(3002, HttpStatus.NOT_FOUND),
    CANNOT_EDIT_HOMESTAY(3003, HttpStatus.FORBIDDEN),
    CANNOT_DELETE_HOMESTAY(3004, HttpStatus.CONFLICT), // Conflict vì đang có booking
    CANNOT_EDIT_TOUR(3005, HttpStatus.FORBIDDEN),
    PROPERTY_UNAVAILABLE(3006, HttpStatus.BAD_REQUEST),
    MAX_GUESTS_EXCEEDED(3007, HttpStatus.BAD_REQUEST),
    INVALID_DATE_RANGE(3008, HttpStatus.BAD_REQUEST),
    CHECK_OUT_BEFORE_CHECK_IN(3009, HttpStatus.BAD_REQUEST),
    AMENITY_NOT_FOUND(3010, HttpStatus.NOT_FOUND),
    DESTINATION_NOT_FOUND(3011, HttpStatus.NOT_FOUND),
    ALREADY_A_HOST(3012, HttpStatus.BAD_REQUEST),
    LOCATION_REQUIRED(3013, HttpStatus.BAD_REQUEST),

    // --- 4xxx: Booking & Payment (Đặt phòng & Thanh toán) ---
    BOOKING_NOT_FOUND(4001, HttpStatus.NOT_FOUND),
    DATES_ALREADY_BOOKED(4002, HttpStatus.CONFLICT), // Trùng lịch đặt phòng
    CANNOT_BOOK_OWN_PROPERTY(4003, HttpStatus.FORBIDDEN),
    BOOKING_ALREADY_CANCELLED(4004, HttpStatus.BAD_REQUEST),
    BOOKING_ALREADY_CONFIRMED(4005, HttpStatus.BAD_REQUEST),
    CANNOT_CANCEL_BOOKING(4006, HttpStatus.BAD_REQUEST),
    PAYMENT_FAILED(4007, HttpStatus.BAD_REQUEST),
    PAYMENT_REQUIRED(4008, HttpStatus.PAYMENT_REQUIRED), // Mã 402 chuẩn chỉnh
    INSUFFICIENT_FUNDS(4009, HttpStatus.BAD_REQUEST),
    INVALID_PROMO_CODE(4010, HttpStatus.BAD_REQUEST),
    PROMO_CODE_EXHAUSTED(4011, HttpStatus.BAD_REQUEST),
    BOOKING_STATUS_INVALID(4012, HttpStatus.BAD_REQUEST),
    REFUND_FAILED(4013, HttpStatus.INTERNAL_SERVER_ERROR),

    // --- 5xxx: Reviews & Ratings (Đánh giá) ---
    REVIEW_NOT_FOUND(5001, HttpStatus.NOT_FOUND),
    REVIEW_NOT_OWNER(5002, HttpStatus.FORBIDDEN),
    CANNOT_EDIT_REVIEW(5003, HttpStatus.FORBIDDEN),
    CANNOT_DELETE_REVIEW(5004, HttpStatus.FORBIDDEN),
    REVIEW_CONTENT_TOO_LONG(5005, HttpStatus.BAD_REQUEST),
    BOOKING_REQUIRED_FOR_REVIEW(5006, HttpStatus.FORBIDDEN), // Phải ở rồi mới được rate
    ALREADY_REVIEWED(5007, HttpStatus.CONFLICT),
    INVALID_RATING_VALUE(5008, HttpStatus.BAD_REQUEST),
    REPLY_NOT_FOUND(5009, HttpStatus.NOT_FOUND),

    // --- 6xxx: Guest & Host Chat ---
    CHAT_ROOM_NOT_FOUND(6001, HttpStatus.NOT_FOUND),
    MESSAGE_NOT_FOUND(6002, HttpStatus.NOT_FOUND),
    MESSAGE_NOT_OWNER(6003, HttpStatus.FORBIDDEN),
    MESSAGE_RECALL_EXPIRED(6004, HttpStatus.BAD_REQUEST),
    MESSAGE_ALREADY_RECALLED(6005, HttpStatus.BAD_REQUEST),
    CANNOT_SEND_TO_SELF(6006, HttpStatus.BAD_REQUEST),
    MESSAGE_ACCESS_DENIED(6007, HttpStatus.FORBIDDEN),
    INTERACTION_RESTRICTED(6008, HttpStatus.FORBIDDEN),

    // --- 7xxx: Media & Uploads (Hình ảnh Homestay/Tour) ---
    FILE_TOO_LARGE(7001, HttpStatus.PAYLOAD_TOO_LARGE), // Mã 413 chuẩn file bự
    UNSUPPORTED_FILE_TYPE(7002, HttpStatus.UNSUPPORTED_MEDIA_TYPE), // Mã 415 chuẩn định dạng
    UPLOAD_FAILED(7003, HttpStatus.INTERNAL_SERVER_ERROR),
    PROPERTY_IMAGE_NOT_FOUND(7004, HttpStatus.NOT_FOUND),
    IMAGE_METADATA_INVALID(7005, HttpStatus.BAD_REQUEST),
    CANNOT_DELETE_PRIMARY_IMAGE(7006, HttpStatus.BAD_REQUEST),
    MAX_IMAGES_REACHED(7007, HttpStatus.BAD_REQUEST),

    // --- 8xxx: Validation Errors ---
    INVALID_EMAIL(8001, HttpStatus.BAD_REQUEST),
    EMAIL_REQUIRED(8002, HttpStatus.BAD_REQUEST),
    PASSWORD_REQUIRED(8003, HttpStatus.BAD_REQUEST),
    PASSWORD_MIN_8_CHARACTERS(8004, HttpStatus.BAD_REQUEST),
    USERNAME_REQUIRED(8005, HttpStatus.BAD_REQUEST),
    FIELD_REQUIRED(8006, HttpStatus.BAD_REQUEST),
    INVALID_INPUT(8007, HttpStatus.BAD_REQUEST),
    USERNAME_LENGTH_INVALID(8008, HttpStatus.BAD_REQUEST),
    CONFIRM_PASSWORD_REQUIRED(8009, HttpStatus.BAD_REQUEST),
    BIRTHDATE_MUST_BE_IN_PAST(8010, HttpStatus.BAD_REQUEST),

    // --- 9xxx: System & Infrastructure ---
    INVALID_REQUEST_FORMAT(9001, HttpStatus.BAD_REQUEST),
    INVALID_KEY(9002, HttpStatus.BAD_REQUEST),
    UPDATE_FAILED(9003, HttpStatus.INTERNAL_SERVER_ERROR),
    DELETE_FAILED(9004, HttpStatus.INTERNAL_SERVER_ERROR),
    CREATE_FAILED(9005, HttpStatus.INTERNAL_SERVER_ERROR),
    DATABASE_ERROR(9006, HttpStatus.SERVICE_UNAVAILABLE),
    INTERNAL_SERVER_ERROR(9007, HttpStatus.INTERNAL_SERVER_ERROR),
    UNCATEGORIZED_EXCEPTION(9999, HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_NOT_FOUND(9008, HttpStatus.INTERNAL_SERVER_ERROR),
    NOTIFICATION_NOT_FOUND(9009, HttpStatus.NOT_FOUND),
    CANNOT_ACCESS_NOTIFICATION(9010, HttpStatus.FORBIDDEN),

    // --- 13xxx: Authorization & SpiceDB (RBAC) ---
    PERMISSION_DENIED(13001, HttpStatus.FORBIDDEN),
    UNAUTHORIZED_ACCESS(13002, HttpStatus.UNAUTHORIZED),
    RESOURCE_OWNER_REQUIRED(13003, HttpStatus.FORBIDDEN),
    SPICEDB_CONNECTION_ERROR(13004, HttpStatus.SERVICE_UNAVAILABLE),
    SPICEDB_WRITE_ERROR(13005, HttpStatus.INTERNAL_SERVER_ERROR),
    SPICEDB_SCHEMA_VIOLATION(13006, HttpStatus.INTERNAL_SERVER_ERROR),
    ROLE_INSUFFICIENT(13007, HttpStatus.FORBIDDEN),
    SPICEDB_READ_ERROR(13011, HttpStatus.INTERNAL_SERVER_ERROR),
    PERMISSION_REVC_FAILED(13012, HttpStatus.INTERNAL_SERVER_ERROR),
    PERMISSION_SYNC_PENDING(13013, HttpStatus.ACCEPTED);

    private final int code;
    private final HttpStatusCode statusCode;

    ResultCode(int code, HttpStatusCode statusCode) {
        this.code = code;
        this.statusCode = statusCode;
    }
}