version: '3.8'

services:
  postgres:
    image: postgres:18
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: ${USERNAME_RSQL}
      POSTGRES_PASSWORD: ${PASSWORD_RSQL}
      POSTGRES_DB: clyvasync
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    networks:
      - backend
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USERNAME_RSQL} -d clyvasync" ]
      interval: 5s
      timeout: 5s
      retries: 5
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${USERNAME_RABBIT}
      RABBITMQ_DEFAULT_PASS: ${PASSWORD_RABBIT}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - backend




  app:
    build: .
    container_name: clyvasync-be
    depends_on:
      postgres:
        condition: service_healthy

    environment:
      DBMSRSQL_CONNECTION: jdbc:postgresql://my-postgres:5432/clyvasync
      USERNAME_RSQL: ${USERNAME_RSQL}
      PASSWORD_RSQL: ${PASSWORD_RSQL}
      RABBITMQ_CONNECTION: rabbitmq
      USERNAME_RABBIT: ${USERNAME_RABBIT}
      PASSWORD_RABBIT: ${PASSWORD_RABBIT}
      USERNAME_MAIL: ${USERNAME_MAIL}
      PASSWORD_MAIL: ${PASSWORD_MAIL}

    ports:
      - "8443:8443"
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  rabbitmqdata:
