services:
  # --- DATABASES ---
  postgres:
    image: postgres:15
    container_name: my-postgres
    restart: always
    environment:
      POSTGRES_USER: ${USERNAME_RSQL}
      POSTGRES_PASSWORD: ${PASSWORD_RSQL}
      POSTGRES_DB: clyvasync_homestay
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - clyvasync-net
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${USERNAME_RSQL:-postgres} -d clyvasync_homestay" ]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5.20
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: ${USERNAME_NSQL}/${PASSWORD_NSQL}
    volumes:
      - neo4jdata:/data
    networks:
      - clyvasync-net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    command: redis-server --requirepass ${PASSWORD_REDIS}
    volumes:
      - redisdata:/data
    networks:
      - clyvasync-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${USERNAME_RABBIT}
      RABBITMQ_DEFAULT_PASS: ${PASSWORD_RABBIT}
    networks:
      - clyvasync-net

  # --- SPICEDB SETUP ---
  db-init:
    image: postgres:15
    environment:
      PGPASSWORD: ${PASSWORD_RSQL:-password}
    command: >
      sh -c "psql -h postgres -U ${USERNAME_RSQL} -d postgres -c 'CREATE DATABASE spicedb;' || true"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - clyvasync-net

  spicedb-migrate:
    image: authzed/spicedb:latest
    command: >
      migrate head 
      --datastore-engine postgres 
      --datastore-conn-uri "postgres://${USERNAME_RSQL}:${PASSWORD_RSQL}@postgres:5432/spicedb?sslmode=disable"
    depends_on:
      db-init:
        condition: service_completed_successfully
    networks:
      - clyvasync-net

  spicedb:
    image: authzed/spicedb:latest
    container_name: spicedb
    restart: always
    command: >
      serve 
      --datastore-engine postgres 
      --datastore-conn-uri "postgres://${USERNAME_RSQL}:${PASSWORD_RSQL}@postgres:5432/spicedb?sslmode=disable"
      --grpc-preshared-key "${SPICEDB_KEY}"
      --http-enabled
    depends_on:
      spicedb-migrate:
        condition: service_completed_successfully
    networks:
      - clyvasync-net

  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka-clyvasync
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.100.11:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
  # --- BACKEND APP ---
  app:
    # QUAN TRỌNG: Dùng image thay vì build
    image: ${IMAGE_NAME}:${BUILD_NUMBER}
    container_name: clyvasync-be
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      spicedb:
        condition: service_started
      redis:
        condition: service_started
      neo4j:
        condition: service_started
    env_file: ..env
    environment:
      SPRING_DATASOURCE_URL: ${DBMSRSQL_CONNECTION}
      SPRING_NEO4J_URI: bolt://neo4j:7687
      SPRING_DATA_REDIS_HOST: redis
      JETCACHE_REMOTE_DEFAULT_HOST: redis
      JETCACHE_REMOTE_DEFAULT_PASSWORD: ${PASSWORD_REDIS}
      SPRING_RABBITMQ_HOST: rabbitmq
      SPICEDB_ENDPOINT: spicedb:50051
      SPICEDB_KEY: ${SPICEDB_KEY}
    networks:
      - clyvasync-net

networks:
  clyvasync-net:
    driver: bridge

volumes:
  pgdata:
  rabbitmqdata:
  redisdata:
  neo4jdata: