spring.application.name=Clyvasync
spring.datasource.url=${DBMSRSQL_CONNECTION}
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=${USERNAME_RSQL}
spring.datasource.password=${PASSWORD_RSQL}
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.flyway.enabled=true

spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

spring.flyway.baseline-on-migrate=true

spring.flyway.locations=classpath:db/migration
spring.flyway.schemas=public

spring.flyway.table=flyway_schema_history
aws.access-key=${S3_ACCESS_KEY}
aws.secret-key=${S3_SECRET_KEY}
aws.region=us-east-1
aws.bucket-name=${BUCKET_NAME}
aws.cloudfront.domain=${CLOUDFRONT_DOMAIN}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${USERNAME_MAIL}
spring.mail.password=${PASSWORD_MAIL}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.rabbitmq.host=${RABBITMQ_CONNECTION}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${USERNAME_RABBIT}
spring.rabbitmq.password=${PASSWORD_RABBIT}
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true

spring.data.redis.host=${REDIS_CONNECTION}
spring.data.redis.port=6379
spring.data.redis.password=${PASSWORD_REDIS}
spring.data.redis.timeout=2000

app.jwt.secret=${JWT_SECRET}
app.jwt.access-token-expiration=3600000
app.jwt.refresh-token-expiration=2592000000

server.port=8080
server.ssl.enabled=false

server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=my-ssl-cert

app.security.password.pepper=${PASSWORD_PEPPER}
spring.messages.basename=messages
spring.messages.encoding=UTF-8
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true
# B\u1EAFt bu\u1ED9c Cookie ch\u1EC9 g\u1EEDi qua HTTPS (V\u00EC SameSite=None y\u00EAu c\u1EA7u Secure)
# Cookie n\u00E0y ph\u1EA3i l\u00E0 Secure v\u00E0 HttpOnly
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.secure=true
server.servlet.session.cookie.same-site=strict
logging.level.org.springframework.security.oauth2.server.authorization=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG

# C\u1EA5u h\u00ECnh chung c\u1EE7a JetCache
jetcache.statIntervalMinutes=15
jetcache.areaInCacheName=false

# L1 Cache (RAM)
jetcache.local.default.type=caffeine
jetcache.local.default.keyConvertor=fastjson2
jetcache.local.default.limit=1000

# L2 Cache (Redis Lettuce)
jetcache.remote.default.type=redis.lettuce
jetcache.remote.default.keyConvertor=fastjson2
jetcache.remote.default.valueEncoder=java
jetcache.remote.default.valueDecoder=java

jetcache.remote.default.uri=redis://${PASSWORD_REDIS}@${REDIS_CONNECTION}:6379/

# C\u1EA5u h\u00ECnh Pool (T\u00F9y ch\u1ECDn)
jetcache.remote.default.poolConfig.minIdle=5
jetcache.remote.default.poolConfig.maxIdle=20
jetcache.remote.default.poolConfig.maxTotal=50